"""Phase 1: Add enrollment number and exam config fields

Revision ID: 068c9787ee43
Revises: cfb70e36d057
Create Date: 2026-05-01 22:51:22.518223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068c9787ee43'
down_revision = 'cfb70e36d057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_marks', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('passing_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('question_paper_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answer_key_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['enrollment_number'])

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_sheet_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('answer_sheet_path')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('enrollment_number')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('answer_key_path')
        batch_op.drop_column('question_paper_path')
        batch_op.drop_column('passing_percentage')
        batch_op.drop_column('max_marks')

    # ### end Alembic commands ###
