"""student onboarding: must_change_password and classroom default_password

Revision ID: 3c90d3a8f1e3
Revises: bd6f33707b28
Create Date: 2026-05-02 20:45:15.313420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c90d3a8f1e3'
down_revision = 'bd6f33707b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_password', sa.String(length=128), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('default_password')

    # ### end Alembic commands ###
