"""Add model_answer and keywords to Assignment

Revision ID: a0cf0fbfaef4
Revises: cbb66688b938
Create Date: 2026-04-30 19:29:21.940535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0cf0fbfaef4'
down_revision = 'cbb66688b938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('model_answer')

    # ### end Alembic commands ###
