"""multiple file uploads

Revision ID: bd6f33707b28
Revises: 068c9787ee43
Create Date: 2026-05-02 15:26:37.336397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd6f33707b28'
down_revision = '068c9787ee43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_paper_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('answer_key_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('answer_key_path')
        batch_op.drop_column('question_paper_path')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_sheet_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('answer_sheet_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_sheet_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('answer_sheet_paths')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_paper_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answer_key_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('answer_key_paths')
        batch_op.drop_column('question_paper_paths')

    # ### end Alembic commands ###
